spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:user-db
    driverClassName: org.h2.Driver
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
